'use strict';

var worker_threads = require('worker_threads');
var promises = require('fs/promises');
var path = require('path');
var dtsBundleGenerator = require('dts-bundle-generator');

async function generateBundle() {
  const { input, output } = worker_threads.workerData;
  const outputDir = path.dirname(output);
  try {
    await promises.access(outputDir, promises.constants.W_OK);
  } catch {
    await promises.mkdir(outputDir, { recursive: true });
  }
  let bundle = dtsBundleGenerator.generateDtsBundle([
    {
      filePath: input
    }
  ]).join("");
  if (bundle?.includes("Generated by dts-bundle-generator")) {
    bundle = bundle.replace(/^\/\/ Generated by dts-bundle-generator.*(\r?\n){1,2}/m, "");
  }
  await promises.writeFile(output, bundle);
}
generateBundle();
